import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{ padding: "1rem", backgroundColor: "#08E8DE", color: "#000" }}
        >
          <h1>My App</h1>
          <nav>
            <Link href="/">Top</Link> | <Link href="/home">Home</Link> |{" "}
            <Link href="/about">About</Link>
          </nav>
        </header>

        <main style={{ padding: "2rem" }}>{children}</main>
      </body>
    </html>
  );
}
