import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Header from "./header/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />

        <main
          style={{
            maxWidth: "70%",
            margin: "0 auto",
            minHeight: "100vh",
            backgroundColor: "#fff",
            color: "#000",
          }}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
